### ISSUE TITLE
crash when /is

### ISSUE THREAD

**Issue by sindronik** [TheSolidCrafter/ASkyBlock-Nukkit#31]
Nukkit latest/ Minecraft: PE server version v1.1.3/ASkyBlock v0.3.7-BETA
----
```
2017-9-28 18:22:24 [CRITICAL] Unhandled exception executing command 'is' in is: java.lang.ClassCastException: cn.nukkit.blockentity.BlockEntitySign cannot be cast to cn.nukkit.blockentity.BlockEntityChest
	at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:541)
	at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:649)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:648)
	at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:211)
	at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:169)
	at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:66)
	at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:55)
	at com.larryTheCoder.Commands.execute(Commands.java:97)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
	at cn.nukkit.Server.dispatchCommand(Server.java:642)
	at cn.nukkit.Player.handleDataPacket(Player.java:3043)
	at cn.nukkit.network.Network.processPackets(Network.java:180)
	at cn.nukkit.network.Network.processBatch(Network.java:151)
	at cn.nukkit.Player.handleDataPacket(Player.java:1908)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:75)
	at cn.nukkit.Server.tick(Server.java:985)
	at cn.nukkit.Server.tickProcessor(Server.java:798)
	at cn.nukkit.Server.start(Server.java:777)
	at cn.nukkit.Server.<init>(Server.java:468)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)

2017-9-28 18:22:24 [ALERT] java.lang.ClassCastException: cn.nukkit.blockentity.BlockEntitySign cannot be cast to cn.nukkit.blockentity.BlockEntityChest
	at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:541)
	at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:649)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:648)
	at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:211)
	at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:169)
	at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:66)
	at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:55)
	at com.larryTheCoder.Commands.execute(Commands.java:97)
	at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
	at cn.nukkit.Server.dispatchCommand(Server.java:642)
	at cn.nukkit.Player.handleDataPacket(Player.java:3043)
	at cn.nukkit.network.Network.processPackets(Network.java:180)
	at cn.nukkit.network.Network.processBatch(Network.java:151)
	at cn.nukkit.Player.handleDataPacket(Player.java:1908)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:75)
	at cn.nukkit.Server.tick(Server.java:985)
	at cn.nukkit.Server.tickProcessor(Server.java:798)
	at cn.nukkit.Server.start(Server.java:777)
	at cn.nukkit.Server.<init>(Server.java:468)
	at cn.nukkit.Nukkit.main(Nukkit.java:68)
```

**Comment by optimusprime338** [comment]
```
[CRITICAL] Unhandled exception executing command 'skyblock' in is: java.lang.ClassCastException: cn.nukkit.blockentity.BlockEntitySign cannot be cast to cn.nukkit.blockentity.BlockEntityChest
        at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:541)
        at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:649)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:648)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:211)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:169)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:66)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:55)
        at com.larryTheCoder.Commands.execute(Commands.java:97)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:643)
        at cn.nukkit.Player.handleDataPacket(Player.java:2525)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:169)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1964)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:990)
        at cn.nukkit.Server.tickProcessor(Server.java:799)
        at cn.nukkit.Server.start(Server.java:778)
        at cn.nukkit.Server.<init>(Server.java:469)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

22:41:56 [ALERT] java.lang.ClassCastException: cn.nukkit.blockentity.BlockEntitySign cannot be cast to cn.nukkit.blockentity.BlockEntityChest
        at com.larryTheCoder.schematic.IslandBlock.paste(IslandBlock.java:541)
        at com.larryTheCoder.schematic.Schematic.lambda$pasteSchematic$1(Schematic.java:649)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at com.larryTheCoder.schematic.Schematic.pasteSchematic(Schematic.java:648)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:211)
        at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:169)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:66)
        at com.larryTheCoder.island.IslandManager.handleIslandCommand(IslandManager.java:55)
        at com.larryTheCoder.Commands.execute(Commands.java:97)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:245)
        at cn.nukkit.Server.dispatchCommand(Server.java:643)
        at cn.nukkit.Player.handleDataPacket(Player.java:2525)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:169)
        at cn.nukkit.network.Network.processBatch(Network.java:151)
        at cn.nukkit.Player.handleDataPacket(Player.java:1964)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:75)
        at cn.nukkit.Server.tick(Server.java:990)
        at cn.nukkit.Server.tickProcessor(Server.java:799)
        at cn.nukkit.Server.start(Server.java:778)
        at cn.nukkit.Server.<init>(Server.java:469)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)
```

**Comment by larryTheCoder** [comment]
This is just a simple fix

**Comment by optimusprime338** [comment]
fix it please @larryTheCoder

**Comment by sindronik** [comment]
and how to fix it? @larryTheCoder
