### ISSUE TITLE
Server crash at start

### ISSUE THREAD

**Issue by PetteriM1** [TheSolidCrafter/ASkyBlock-Nukkit#35]
13:25:23 [INFO] Loading ASkyBlock v0.3.7-BETA
13:25:23 [INFO] [ASkyBlock] Seccessfully checked config.yml
```java 
java.lang.IllegalAccessError: class org.sqlite.SQLiteConfig$TransactionMode cannot access its superinterface org.sqlite.SQLiteConfig$PragmaValue
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at cn.nukkit.plugin.JavaPluginLoader.getClassByName(JavaPluginLoader.java:141)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:40)
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.sqlite.core.CoreConnection.<clinit>(CoreConnection.java:46)
        at org.sqlite.JDBC.createConnection(JDBC.java:114)
        at org.sqlite.JDBC.connect(JDBC.java:88)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at com.larryTheCoder.database.variables.SQLiteDatabase.openConnection(SQLiteDatabase.java:52)
        at com.larryTheCoder.database.ASConnection.<init>(ASConnection.java:51)
        at com.larryTheCoder.ASkyBlock.initDatabase(ASkyBlock.java:266)
        at com.larryTheCoder.ASkyBlock.onLoad(ASkyBlock.java:227)
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:105)
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:53)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:268)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.<init>(Server.java:392)
        at cn.nukkit.Nukkit.main(Nukkit.java:68)

**Comment by larryTheCoder** [comment]
Check your DbLib usually this is caused by newer build of DbLib 
Duplicate with #9

**Comment by NycuRO** [comment]
@larryTheCoder Update coming?

**Comment by NycuRO** [comment]
I want commit.
