### ISSUE TITLE
cant create level!

### ISSUE THREAD

**Issue by optimusprime338** [TheSolidCrafter/ASkyBlock-Nukkit#36]
### Issue Description
Write a short description about the issue

### Steps to Reproduce the Issue

1. type /is
2. configure in GUI
3. Adfter submit says on screen:-  Cannot attempt to generate level. PC type of schematic!

### OS and Versions

* ASkyBlock version:

* Nukkit Version: ?? 

* Java Version: 
```
??
```

* Host Configuration: 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | Windows 10
| Client Version | ?? | 1.2.3

### Crashdump, Backtrace or Other Files

```
2017-11-8 03:50:53 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerFormRespondedEvent' to 'ASkyBlock v0.3.7-BETA': null on com.larryTheCoder.panels.Panel
2017-11-8 03:50:53 [ALERT] cn.nukkit.utils.EventException
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
	at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
	at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
	at cn.nukkit.Player.handleDataPacket(Player.java:2409)
	at java.util.ArrayList.forEach(Unknown Source)
	at cn.nukkit.network.Network.processPackets(Network.java:178)
	at cn.nukkit.network.Network.processBatch(Network.java:160)
	at cn.nukkit.Player.handleDataPacket(Player.java:1985)
	at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
	at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
	at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
	at cn.nukkit.network.Network.processInterfaces(Network.java:76)
	at cn.nukkit.Server.tick(Server.java:998)
	at cn.nukkit.Server.tickProcessor(Server.java:801)
	at cn.nukkit.Server.start(Server.java:780)
	at cn.nukkit.Server.<init>(Server.java:471)
	at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
	at com.larryTheCoder.schematic.SchematicHandler.pasteSchematic(SchematicHandler.java:530)
	at com.larryTheCoder.island.IslandManager.createIsland(IslandManager.java:204)
	at com.larryTheCoder.panels.Panel.onPlayerRespondForm(Panel.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
	... 16 more
```

**Comment by larryTheCoder** [comment]
Yes PC Type of schematic. You need to use the default skyblock schematic because bugs is confirmed by the PC schematic.

This plugin using PC schematic and will be changed soon

**Comment by optimusprime338** [comment]
@larryTheCoder 
![image](https://user-images.githubusercontent.com/27479208/32587429-4d3e18ca-c52e-11e7-84f0-743a760b54a7.png)

**Comment by larryTheCoder** [comment]
Uh how u get there? i thought i just blocked anyone from getting that unfinished island xD

**Comment by optimusprime338** [comment]
well it created but messed up . and there is no starter chest!

**Comment by larryTheCoder** [comment]
For your correction. There is a starter chest but underneath

**Comment by optimusprime338** [comment]
let me check lol

**Comment by optimusprime338** [comment]
there is XD

**Comment by PetteriM1** [comment]
Is this fixed soon?

**Comment by NycuR0** [comment]
Any update @larryTheCoder ?

**Comment by larryTheCoder** [comment]
Soon as fast as possible
