### ISSUE TITLE
Error if other plugins use form windows

### ISSUE THREAD

**Issue by PetteriM1** [TheSolidCrafter/ASkyBlock-Nukkit#39]
[CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerFormRespondedEvent' to 'ASkyBlock': null on com.larryTheCoder.panels.Panel
[ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:553)
        at cn.nukkit.Player.handleDataPacket(Player.java:2418)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:1960)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1012)
        at cn.nukkit.Server.tickProcessor(Server.java:805)
        at cn.nukkit.Server.start(Server.java:784)
        at cn.nukkit.Server.<init>(Server.java:470)
        at cn.nukkit.Nukkit.main(Nukkit.java:97)
Caused by: java.lang.NullPointerException
        at com.larryTheCoder.panels.Panel.onPlayerRespondForm(Panel.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 16 more

**Comment by PetteriM1** [comment]
I use this as fix:
if (event.getResponse()==null) { return; }
