### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by UnexMC** [TheSolidCrafter/ASkyBlock-Nukkit#42]
```
21:24:07 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerCommandPreprocessEvent' to 'ASkyBlock v0.3.7-BETA': null on com.larryTheCoder.listener.IslandGuard
21:24:07 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:542)
        at cn.nukkit.Player.handleDataPacket(Player.java:2617)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2022)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1074)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:508)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
        at com.larryTheCoder.listener.IslandGuard.inWorld(IslandGuard.java:110)
        at com.larryTheCoder.listener.IslandGuard.inWorld(IslandGuard.java:89)
        at com.larryTheCoder.listener.IslandGuard.onPlayerCommand(IslandGuard.java:1415)
        at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 16 more
```

**Comment by UnexMC** [comment]
21:26:58 [CRITICAL] Could not pass event 'cn.nukkit.event.player.PlayerFormRespondedEvent' to 'ASkyBlock v0.3.7-BETA': null on com.larryTheCoder.panels.Panel
21:26:58 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:542)
        at cn.nukkit.Player.handleDataPacket(Player.java:2488)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2022)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1074)
        at cn.nukkit.Server.tickProcessor(Server.java:848)
        at cn.nukkit.Server.start(Server.java:825)
        at cn.nukkit.Server.<init>(Server.java:508)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
        at com.larryTheCoder.panels.Panel.onPlayerRespondForm(Panel.java:71)
        at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 16 more

**Comment by UnexMC** [comment]
What about adding /is join or /is go

**Comment by larryTheCoder** [comment]
First how do you get the IslandGuard error? Do you use other world? Need to know what do you do until you get this bug, but the panel is reproducible, its maybe because that other player is using other Forms when this bug happens

**Comment by UnexMC** [comment]
15:59:22 [CRITICAL] Unhandled exception executing command 'is teleport HappyLea13' in is: java.lang.NullPointerException        at com.larryTheCoder.island.IslandManager.teleportPlayer(IslandManager.java:334)
        at com.larryTheCoder.command.island.TeleportSubCommand.execute(TeleportSubCommand.java:65)
        at com.larryTheCoder.Commands.execute(Commands.java:105)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:261)
        at cn.nukkit.Server.dispatchCommand(Server.java:690)
        at cn.nukkit.Player.handleDataPacket(Player.java:2632)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2025)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1076)
        at cn.nukkit.Server.tickProcessor(Server.java:850)
        at cn.nukkit.Server.start(Server.java:827)
        at cn.nukkit.Server.<init>(Server.java:510)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

15:59:22 [ALERT] java.lang.NullPointerException
        at com.larryTheCoder.island.IslandManager.teleportPlayer(IslandManager.java:334)
        at com.larryTheCoder.command.island.TeleportSubCommand.execute(TeleportSubCommand.java:65)
        at com.larryTheCoder.Commands.execute(Commands.java:105)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:261)
        at cn.nukkit.Server.dispatchCommand(Server.java:690)
        at cn.nukkit.Player.handleDataPacket(Player.java:2632)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2025)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1076)
        at cn.nukkit.Server.tickProcessor(Server.java:850)
        at cn.nukkit.Server.start(Server.java:827)
        at cn.nukkit.Server.<init>(Server.java:510)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)

**Comment by NycuRO** [comment]
fixed?

**Comment by larryTheCoder** [comment]
I already fixed this issue. Hmm
