### ISSUE TITLE
Claiming issue

### ISSUE THREAD

**Issue by Cobwebster** [TheSolidCrafter/ASkyBlock-Nukkit#44]
Latest dev build, seems like claiming is broke. the plugin works fine but there is no actual protection anywhere. you're not limited to your IS radius and anyone can build on any island. Big issue. 

Not sure if this error is related,
java.lang.UnsupportedOperationException: Chunk is outside population area
	at cn.nukkit.level.generator.PopChunkManager.setChunk(PopChunkManager.java:76)
	at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:101)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
	at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43)
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by larryTheCoder** [comment]
Well this is chaos actually. But the bug is not related to this

**Comment by Cobwebster** [comment]
What is the bug related to so I can report it there?

**Comment by larryTheCoder** [comment]
Okay, its been fixed now, Tested it and seems like it was the bug from incorrect usage of some functions. But it should be working now

**Comment by Cobwebster** [comment]
Doesn't look fixed,

11:47:28 [CRITICAL] Could not pass event 'cn.nukkit.event.block.BlockPlaceEvent' to 'ASkyBlock v0.3.9-STABLE': null on com.larryTheCoder.listener.IslandGuard
11:47:28 [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:542)
        at cn.nukkit.level.Level.useItemOn(Level.java:2065)
        at cn.nukkit.level.Level.useItemOn(Level.java:1941)
        at cn.nukkit.Player.handleDataPacket(Player.java:2848)
        at java.util.ArrayList.forEach(Unknown Source)
        at cn.nukkit.network.Network.processPackets(Network.java:178)
        at cn.nukkit.network.Network.processBatch(Network.java:160)
        at cn.nukkit.Player.handleDataPacket(Player.java:2025)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66)
        at cn.nukkit.network.Network.processInterfaces(Network.java:76)
        at cn.nukkit.Server.tick(Server.java:1076)
        at cn.nukkit.Server.tickProcessor(Server.java:850)
        at cn.nukkit.Server.start(Server.java:827)
        at cn.nukkit.Server.<init>(Server.java:510)
        at cn.nukkit.Nukkit.main(Nukkit.java:99)
Caused by: java.lang.NullPointerException
        at com.larryTheCoder.listener.IslandGuard.onPlayerBlockPlace(IslandGuard.java:1132)
        at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 18 more

and I can still place blocks way off my IS. 

Nukkit error,
[CRITICAL] Exception in asynchronous task
java.lang.UnsupportedOperationException: Chunk is outside population area
        at cn.nukkit.level.generator.PopChunkManager.setChunk(PopChunkManager.java:76)
        at cn.nukkit.level.generator.task.PopulationTask.generationTask(PopulationTask.java:101)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:48)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.syncGen(PopulationTask.java:53)
        at cn.nukkit.level.generator.task.PopulationTask.onRun(PopulationTask.java:43)
        at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by Cobwebster** [comment]
Any update on this? Should I test the latest build?

**Comment by larryTheCoder** [comment]
It probably be fixed now.

**Comment by Cobwebster** [comment]
@larryTheCoder Doesn't look like it, the error was still there after testing the latest version. I then reset my worlds and everything to do with skyblock + the server, fresh start to test and it juts rejects my connection with this error,

https://pastebin.com/jHikWR6q

^-- that error + the original error on block place outside of claim.

**Comment by Cobwebster** [comment]
Error upon making a new island - https://pastebin.com/xdiApbR3
Fresh server with latest nukkit, default IS settings with default panel options. 

Currently unable to confirm if the protection issue is resolved because of this.

**Comment by larryTheCoder** [comment]
Wait a second @Cobwebster you are using the old build of ASkyBlock. The latest one fixed this issue. This issue here is considered as closed... You are using old ones.

**Comment by Cobwebster** [comment]
Could you link the download? I'm pretty sure i hit the latest link and went to the artifacts.
